Repository Seagate/cortx-hare, pull requests merged in 2022-09, with the labels that each got.

#2156 Enable Fault Injection service for motr
  cfgen/cfgen
Labels: cla-signed

#2123 CORTX-30537: add a way to disable formulaic pool versions
  cfgen/cfgen
  cfgen/dhall/types/ClusterDesc.dhall
  cfgen/examples/singlenode.yaml
  cfgen/tests/singlenode.dhall
  provisioning/miniprov/hare_mp/cdf.py
  provisioning/miniprov/hare_mp/dhall/gencdf.dhall
  provisioning/miniprov/hare_mp/types.py
Labels: cla-signed, Status: Checks Failed

#2153 CORTX-28971: update service fids along with process fids
  hax/hax/handler.py
  hax/hax/motr/__init__.py
  hax/hax/types.py
  hax/hax/util.py
  hax/test/integration/test_motr.py
  hax/test/test_failure.py
Labels: cla-signed

#2161 CORTX-34086: m0crate IO failure
  utils/m0crate-io-conf
Labels: cla-signed

#2159 CORTX-34159: Address and fix Codacy issues in C file (hax.c)
  hax/hax/motr/hax.c
Labels: cla-signed

#2147 Update Codacy Badge
  README.md
Labels: cla-signed, Status: Waiting to be Reviewed

#2163 CORTX-34147: Add time stamp for consul process state updated in bq
  hax/hax/handler.py
  hax/hax/queue/publish.py
  utils/hare-reportbug
Labels: cla-signed
